# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'az-tenant'
    KeyVaultName: 'az-hopkins-demo22-kv'
    SecretsFilter: "*"
    RunAsPreJob: true
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo "-- Build Env Vars --"
      echo $(demodbhost)
      echo $(demodbuser)
      echo $testEnvVal
      echo "-- Build Env Vars --"
    env:
      testEnvVal: 'test-env-value1234'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  env:
    AZ_DB_CSTR_HOST: $(demodbhost)
    AZ_DB_CSTR_DB: $(demodbtarget)
    AZ_DB_CSTR_USER: $(demodbuser)
    AZ_DB_CSTR_PWD: $(demodbpwd)
