# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  batch: true
  branches:  
    include: 
    - main
    - dev

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'az-tenant'
    KeyVaultName: 'az-hopkins-demo22-kv'
    SecretsFilter: "*"
    RunAsPreJob: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo "-- Build Env Vars --"
      echo $(demodbhost)
      echo $(demodbuser)
      echo "-- Build Env Vars --"
    

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  env:
    AZ_DB_CSTR_HOST: $(demodbhost)
    AZ_DB_CSTR_DB: $(demodbtarget)
    AZ_DB_CSTR_USER: $(demodbuser)
    AZ_DB_CSTR_PWD: $(demodbpwd)
    AZ_ID_TENANT: $(aztenantid)
    AZ_ID_CLIENTID: $(azclientid)
    AZ_ID_SECRET: $(azclientsecret)
    AZ_ID_APPURI: $(azappuri)
    AZ_SSL_KEY_ALIAS: $(sslkeyalias)
    AZ_SSL_KEY_STORETYPE: $(sslkeystoretype)
    AZ_SSL_KEY_TRUST_STORETYPE: $(ssltruststoretype)
    AZ_SSL_KEYVAULT_URI: $(azkeyvaulturi)

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'az-tenant'
    Action: 'Deploy'
    AzureSpringCloud: 'hopkins-demo22-api-sc'
    AppName: 'hopkins-demo22-api'
    UseStagingDeployment: false
    DeploymentName: 'default'
  env:
    AZ_DB_CSTR_HOST: $(demodbhost)
    AZ_DB_CSTR_DB: $(demodbtarget)
    AZ_DB_CSTR_USER: $(demodbuser)
    AZ_DB_CSTR_PWD: $(demodbpwd)


